import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'
import { ValidationReport } from './report-generator'

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2px solid #10B981',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
  },
  scoreSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  scoreCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scoreValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#10B981',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  paragraph: {
    fontSize: 11,
    color: '#374151',
    lineHeight: 1.6,
    marginBottom: 8,
  },
  listItem: {
    fontSize: 11,
    color: '#374151',
    marginBottom: 4,
    marginLeft: 10,
  },
  greenLight: {
    color: '#059669',
  },
  redFlag: {
    color: '#DC2626',
  },
  table: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  tableHeader: {
    backgroundColor: '#F9FAFB',
    fontWeight: 'bold',
  },
  tableCell: {
    flex: 1,
    padding: 8,
    fontSize: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#9CA3AF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
})

interface ReportPDFProps {
  ideaTitle: string
  report: ValidationReport
}

export const ReportPDF: React.FC<ReportPDFProps> = ({ ideaTitle, report }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>Validation Report</Text>
        <Text style={styles.subtitle}>{ideaTitle}</Text>
        <Text style={styles.subtitle}>Generated by IdeaValidationLite</Text>
      </View>

      {/* Score */}
      <View style={styles.scoreSection}>
        <View style={styles.scoreCircle}>
          <Text style={styles.scoreValue}>{report.overallScore}</Text>
        </View>
        <Text style={{ fontSize: 12, color: '#6B7280', marginLeft: 15 }}>
          Overall Validation Score
        </Text>
      </View>

      {/* Executive Summary */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.paragraph}>{report.executiveSummary}</Text>
      </View>

      {/* GO/NO-GO Recommendation */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Recommendation</Text>
        <View style={{ backgroundColor: report.goNoGoRecommendation.recommendation === 'GO' ? '#D1FAE5' : '#FEE2E2', padding: 12, borderRadius: 6, marginBottom: 8 }}>
          <Text style={{ fontSize: 14, fontWeight: 'bold', color: report.goNoGoRecommendation.recommendation === 'GO' ? '#065F46' : '#991B1B' }}>
            {report.goNoGoRecommendation.recommendation === 'GO' ? '✓ GO' : report.goNoGoRecommendation.recommendation === 'NO-GO' ? '✕ NO-GO' : '⚠ CONDITIONAL GO'}
          </Text>
          <Text style={{ fontSize: 10, color: '#374151', marginTop: 4 }}>
            Confidence: {report.goNoGoRecommendation.confidence}%
          </Text>
        </View>
        <Text style={styles.paragraph}>{report.goNoGoRecommendation.rationale}</Text>
        {report.goNoGoRecommendation.keyConditions && report.goNoGoRecommendation.keyConditions.length > 0 && (
          <View>
            <Text style={{ fontSize: 10, fontWeight: 'bold', color: '#374151', marginTop: 6 }}>Key Conditions:</Text>
            {report.goNoGoRecommendation.keyConditions.map((condition, i) => (
              <Text key={i} style={styles.listItem}>• {condition}</Text>
            ))}
          </View>
        )}
      </View>

      {/* Green Lights */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>
          <Text style={styles.greenLight}>✓ </Text> Green Lights
        </Text>
        {report.greenLights.map((light, i) => (
          <Text key={i} style={styles.listItem}>• {light}</Text>
        ))}
      </View>

      {/* Red Flags */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>
          <Text style={styles.redFlag}>⚠ </Text> Red Flags
        </Text>
        {report.redFlags.map((flag, i) => (
          <Text key={i} style={styles.listItem}>• {flag}</Text>
        ))}
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by IdeaValidationLite | Page 1 of 3
      </Text>
    </Page>

    {/* Page 2 */}
    <Page size="A4" style={styles.page}>
      {/* SWOT Analysis */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>SWOT Analysis</Text>
        <View style={{ marginBottom: 10 }}>
          <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#059669', marginBottom: 4 }}>Strengths</Text>
          {report.swotAnalysis.strengths.map((item, i) => (
            <Text key={i} style={styles.listItem}>• {item}</Text>
          ))}
        </View>
        <View style={{ marginBottom: 10 }}>
          <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#DC2626', marginBottom: 4 }}>Weaknesses</Text>
          {report.swotAnalysis.weaknesses.map((item, i) => (
            <Text key={i} style={styles.listItem}>• {item}</Text>
          ))}
        </View>
        <View style={{ marginBottom: 10 }}>
          <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#2563EB', marginBottom: 4 }}>Opportunities</Text>
          {report.swotAnalysis.opportunities.map((item, i) => (
            <Text key={i} style={styles.listItem}>• {item}</Text>
          ))}
        </View>
        <View>
          <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#DC2626', marginBottom: 4 }}>Threats</Text>
          {report.swotAnalysis.threats.map((item, i) => (
            <Text key={i} style={styles.listItem}>• {item}</Text>
          ))}
        </View>
      </View>

      {/* Target Audience */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Target Audience</Text>
        <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#1F2937', marginBottom: 4 }}>Primary ICP</Text>
        <Text style={styles.paragraph}>{report.targetAudience.primaryICP}</Text>
        <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#1F2937', marginBottom: 4, marginTop: 8 }}>Demographics</Text>
        <Text style={styles.paragraph}>{report.targetAudience.demographics}</Text>
        <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#1F2937', marginBottom: 4, marginTop: 8 }}>Psychographics</Text>
        <Text style={styles.paragraph}>{report.targetAudience.psychographics}</Text>
        <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#1F2937', marginBottom: 4, marginTop: 8 }}>Pain Points</Text>
        {report.targetAudience.painPoints.map((pain, i) => (
          <Text key={i} style={styles.listItem}>• {pain}</Text>
        ))}
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by IdeaValidationLite | Page 2 of 3
      </Text>
    </Page>

    {/* Page 3 */}
    <Page size="A4" style={styles.page}>
      {/* Risk Matrix */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Risk Matrix</Text>
        {report.riskMatrix.map((riskItem, i) => (
          <View key={i} style={{ borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 6, padding: 8, marginBottom: 8 }}>
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 }}>
              <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#1F2937' }}>{riskItem.risk}</Text>
              <Text style={{ fontSize: 10, color: riskItem.level === 'HIGH' ? '#DC2626' : riskItem.level === 'MEDIUM' ? '#F59E0B' : '#059669', backgroundColor: riskItem.level === 'HIGH' ? '#FEE2E2' : riskItem.level === 'MEDIUM' ? '#FEF3C7' : '#D1FAE5', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 }}>
                {riskItem.level} RISK
              </Text>
            </View>
            <Text style={{ fontSize: 9, color: '#6B7280', marginBottom: 2 }}>
              Impact: {riskItem.impact} | Likelihood: {riskItem.likelihood}
            </Text>
            <Text style={{ fontSize: 10, color: '#374151' }}>
              <Text style={{ fontWeight: 'bold' }}>Mitigation: </Text>{riskItem.mitigation}
            </Text>
          </View>
        ))}
      </View>

      {/* Revenue Model Suggestions */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Revenue Model Suggestions</Text>
        {report.revenueModelSuggestions.map((model, i) => (
          <View key={i} style={{ borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 6, padding: 8, marginBottom: 8 }}>
            <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#1F2937', marginBottom: 2 }}>{model.model}</Text>
            <Text style={{ fontSize: 10, color: '#6B7280', marginBottom: 4 }}>{model.description}</Text>
            <View style={{ flexDirection: 'row', marginBottom: 4 }}>
              <View style={{ flex: 1, marginRight: 8 }}>
                <Text style={{ fontSize: 9, fontWeight: 'bold', color: '#059669' }}>Pros:</Text>
                {model.pros.map((pro, j) => (
                  <Text key={j} style={{ fontSize: 9, color: '#374151', marginLeft: 8 }}>• {pro}</Text>
                ))}
              </View>
              <View style={{ flex: 1 }}>
                <Text style={{ fontSize: 9, fontWeight: 'bold', color: '#DC2626' }}>Cons:</Text>
                {model.cons.map((con, j) => (
                  <Text key={j} style={{ fontSize: 9, color: '#374151', marginLeft: 8 }}>• {con}</Text>
                ))}
              </View>
            </View>
            <Text style={{ fontSize: 9, color: '#1F2937', fontWeight: 'bold' }}>Est. MRR: {model.estimatedMRR}</Text>
          </View>
        ))}
      </View>

      {/* Recommendations */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Recommendations</Text>
        {report.recommendations.map((rec, i) => (
          <Text key={i} style={styles.listItem}>
            {i + 1}. {rec}
          </Text>
        ))}
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by IdeaValidationLite | Page 3 of 3
      </Text>
    </Page>
  </Document>
)

export async function generatePDF(ideaTitle: string, report: ValidationReport): Promise<Blob> {
  const pdfInstance = <ReportPDF ideaTitle={ideaTitle} report={report} />
  return pdf(pdfInstance).toBlob()
}
