import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'
import { ValidationReport } from './report-generator'

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2px solid #10B981',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
  },
  scoreSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  scoreCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scoreValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#10B981',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  paragraph: {
    fontSize: 11,
    color: '#374151',
    lineHeight: 1.6,
    marginBottom: 8,
  },
  listItem: {
    fontSize: 11,
    color: '#374151',
    marginBottom: 4,
    marginLeft: 10,
  },
  greenLight: {
    color: '#059669',
  },
  redFlag: {
    color: '#DC2626',
  },
  table: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  tableHeader: {
    backgroundColor: '#F9FAFB',
    fontWeight: 'bold',
  },
  tableCell: {
    flex: 1,
    padding: 8,
    fontSize: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#9CA3AF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
})

interface ReportPDFProps {
  ideaTitle: string
  report: ValidationReport
}

export const ReportPDF: React.FC<ReportPDFProps> = ({ ideaTitle, report }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>Validation Report</Text>
        <Text style={styles.subtitle}>{ideaTitle}</Text>
        <Text style={styles.subtitle}>Generated by IdeaValidationLite</Text>
      </View>

      {/* Score */}
      <View style={styles.scoreSection}>
        <View style={styles.scoreCircle}>
          <Text style={styles.scoreValue}>{report.overallScore}</Text>
        </View>
        <Text style={{ fontSize: 12, color: '#6B7280', marginLeft: 15 }}>
          Overall Validation Score
        </Text>
      </View>

      {/* Executive Summary */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.paragraph}>{report.executiveSummary}</Text>
      </View>

      {/* Green Lights */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>
          <Text style={styles.greenLight}>✓ </Text> Green Lights
        </Text>
        {report.greenLights.map((light, i) => (
          <Text key={i} style={styles.listItem}>• {light}</Text>
        ))}
      </View>

      {/* Red Flags */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>
          <Text style={styles.redFlag}>⚠ </Text> Red Flags
        </Text>
        {report.redFlags.map((flag, i) => (
          <Text key={i} style={styles.listItem}>• {flag}</Text>
        ))}
      </View>

      {/* Market Size */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Market Size</Text>
        <View style={styles.table}>
          <View style={styles.tableRow}>
            <Text style={[styles.tableCell, styles.tableHeader]}>TAM</Text>
            <Text style={[styles.tableCell, styles.tableHeader]}>SAM</Text>
            <Text style={[styles.tableCell, styles.tableHeader]}>SOM</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableCell}>{report.marketSize.TAM}</Text>
            <Text style={styles.tableCell}>{report.marketSize.SAM}</Text>
            <Text style={styles.tableCell}>{report.marketSize.SOM}</Text>
          </View>
        </View>
      </View>

      {/* Competitors */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Competitors</Text>
        {report.competitors.map((competitor, i) => (
          <View key={i} style={{ marginBottom: 10 }}>
            <Text style={{ fontSize: 12, fontWeight: 'bold', color: '#1F2937' }}>
              {competitor.name}
            </Text>
            <Text style={styles.paragraph}>{competitor.description}</Text>
            <Text style={{ fontSize: 10, color: '#10B981' }}>
              Differentiation: {competitor.differentiation}
            </Text>
          </View>
        ))}
      </View>

      {/* Recommendations */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Recommendations</Text>
        {report.recommendations.map((rec, i) => (
          <Text key={i} style={styles.listItem}>
            {i + 1}. {rec}
          </Text>
        ))}
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by IdeaValidationLite | Page 1 of 1
      </Text>
    </Page>
  </Document>
)

export async function generatePDF(ideaTitle: string, report: ValidationReport): Promise<Blob> {
  const pdfInstance = <ReportPDF ideaTitle={ideaTitle} report={report} />
  return pdf(pdfInstance).toBlob()
}
